# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HW3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7.0'
  pod 'SwiftyJSON', '~> 3.0'
  pod 'AlamofireImage', '~> 3.4'
  # Pods for HW3

end
